#!/usr/bin/env bash
# Opens an onboarding PR in the target repo.
# All inputs come from environment variables set by the calling workflow.
set -euo pipefail

BRANCH="sonar-fix/onboarding"
WORKFLOW_DIR=".github/workflows"
CONFIG_DIR=".github"

# ── Clone target repo ────────────────────────────────────────────────────────
git clone "https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git" /tmp/target-repo
cd /tmp/target-repo

git config user.email "github-actions[bot]@users.noreply.github.com"
git config user.name  "github-actions[bot]"

# Unset extraheader so the PAT in the URL wins auth
git config --unset-all http.https://github.com/.extraheader || true

# ── Create branch (reset if already exists) ──────────────────────────────────
git checkout -B "$BRANCH"

# ── Write sonar-fix caller workflow ──────────────────────────────────────────
mkdir -p "$WORKFLOW_DIR"

ONBOARDING_REPO_URL="https://github.com/${ONBOARDING_REPO}"

if [ "$TRIGGER" = "comment-triggered" ]; then
  WORKFLOW_TEMPLATE="caller-comment-triggered.yml"
else
  WORKFLOW_TEMPLATE="caller-pr-triggered.yml"
fi

# Fetch the template from the central sonar-fix repo at main
SONAR_FIX_RAW="https://raw.githubusercontent.com/${ONBOARDING_REPO%/*}/sonar-autofix-on-pr/main/examples/${WORKFLOW_TEMPLATE}"
curl -sf "$SONAR_FIX_RAW" -o "${WORKFLOW_DIR}/sonar-fix.yml"

# ── Write sonar-fix-config.yml (only if overrides provided) ──────────────────
if [ -n "$CONFIG_OVERRIDES" ]; then
  cat > "${CONFIG_DIR}/sonar-fix-config.yml" <<EOF
# sonar-fix config overrides — generated by sonar-fix-onboarding
# Full option reference: https://github.com/${ONBOARDING_REPO}
${CONFIG_OVERRIDES}
EOF
fi

# ── Commit and push ───────────────────────────────────────────────────────────
git add .
git diff --cached --quiet && echo "No changes to commit." && exit 0

git commit -m "chore: add sonar-fix automated issue fixing

Added by sonar-fix-onboarding (issue ${ONBOARDING_REPO}#${ISSUE_NUMBER}).
Agent: ${AGENT} | Trigger: ${TRIGGER} | Project: ${PROJECT_KEY}
Token: ${TOKEN_NAME}"

git push --force-with-lease origin "$BRANCH"

# ── Open PR ───────────────────────────────────────────────────────────────────
PR_URL=$(gh pr create \
  --repo "$TARGET_REPO" \
  --head "$BRANCH" \
  --base "$(git remote show origin | awk '/HEAD branch/ {print $NF}')" \
  --title "chore: add sonar-fix automated SonarQube issue fixing" \
  --body "$(cat <<EOF
## sonar-fix Onboarding

This PR was automatically generated by [sonar-fix-onboarding](https://github.com/${ONBOARDING_REPO}) in response to issue #${ISSUE_NUMBER}.

### What's included

- \`.github/workflows/sonar-fix.yml\` — the sonar-fix caller workflow (${TRIGGER})
$([ -n "$CONFIG_OVERRIDES" ] && echo "- \`.github/sonar-fix-config.yml\` — your config overrides" || echo "- No config overrides — central defaults apply")

### What was set up for you

- \`SONAR_TOKEN\` secret — scoped project analysis token for \`${PROJECT_KEY}\`
- \`SONAR_PROJECT_KEY\` variable — \`${PROJECT_KEY}\`
- \`SONAR_HOST_URL\` variable

### Next steps

1. Review the workflow file and adjust if needed
2. Merge this PR
3. Open a PR that introduces code with SonarQube issues to see sonar-fix in action

### Agent

**${AGENT}** — make sure the corresponding API key secret is set at the org level:
$(case "$AGENT" in
  claude) echo "- \`ANTHROPIC_API_KEY\`";;
  codex)  echo "- \`OPENAI_API_KEY\`";;
  copilot) echo "- \`COPILOT_PAT\` (must have Copilot access)";;
esac)

---
*Requested via [sonar-fix-onboarding#${ISSUE_NUMBER}](https://github.com/${ONBOARDING_REPO}/issues/${ISSUE_NUMBER})*
EOF
)" 2>&1 || true)

echo "PR: $PR_URL"
echo "pr_url=${PR_URL}" >> "$GITHUB_OUTPUT" 2>/dev/null || true
