#!/usr/bin/env bash
# Opens an onboarding PR in the target repo.
# All inputs come from environment variables set by the calling workflow.
set -euo pipefail

BRANCH="sonar-fix/onboarding"
WORKFLOW_DIR=".github/workflows"
CONFIG_DIR=".github"

# ── Clone target repo ────────────────────────────────────────────────────────
git clone "https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git" /tmp/target-repo
cd /tmp/target-repo

git config user.email "github-actions[bot]@users.noreply.github.com"
git config user.name  "github-actions[bot]"

# Unset extraheader so the PAT in the URL wins auth
git config --unset-all http.https://github.com/.extraheader || true

# ── Create branch (reset if already exists) ──────────────────────────────────
git checkout -B "$BRANCH"

# ── Write sonar-fix caller workflow ──────────────────────────────────────────
mkdir -p "$WORKFLOW_DIR"

if [ "$TRIGGER" = "comment-triggered" ]; then
  WORKFLOW_TEMPLATE="caller-comment-triggered.yml"
else
  WORKFLOW_TEMPLATE="caller-pr-triggered.yml"
fi

# Fetch the template from the central sonar-fix repo at main
SONAR_FIX_RAW="https://raw.githubusercontent.com/${ONBOARDING_REPO%/*}/sonar-autofix-on-pr/main/examples/${WORKFLOW_TEMPLATE}"
curl -sf "$SONAR_FIX_RAW" -o "${WORKFLOW_DIR}/sonar-fix.yml"

# ── Write sonar-fix-config.yml (only if overrides provided) ──────────────────
if [ -n "$CONFIG_OVERRIDES" ]; then
  cat > "${CONFIG_DIR}/sonar-fix-config.yml" <<EOF
# sonar-fix config overrides — generated by sonar-fix-onboarding
# Full option reference: https://github.com/${ONBOARDING_REPO}
${CONFIG_OVERRIDES}
EOF
fi

# ── Commit and push ───────────────────────────────────────────────────────────
git add .
git diff --cached --quiet && echo "No changes to commit." && exit 0

git commit -m "chore: add sonar-fix automated issue fixing

Added by sonar-fix-onboarding (issue ${ONBOARDING_REPO}#${ISSUE_NUMBER}).
Agent: ${AGENT} | Trigger: ${TRIGGER} | Project: ${PROJECT_KEY}
Token: ${TOKEN_NAME}"

git push --force-with-lease origin "$BRANCH"

# ── Open PR ───────────────────────────────────────────────────────────────────
if [ "$PROJECT_CREATED" = "true" ]; then
  PROJECT_NOTE="- \`.github/sonar-fix-config.yml\` — your config overrides"
  SONAR_NOTE="> **Note:** A new SonarCloud project \`${PROJECT_KEY}\` was created and bound to this repo. It will begin analyzing PRs automatically once this workflow is merged."
else
  SONAR_NOTE="> SonarCloud project \`${PROJECT_KEY}\` was found and is already configured."
fi

gh pr create \
  --repo "$TARGET_REPO" \
  --head "$BRANCH" \
  --base "$(git remote show origin | awk '/HEAD branch/ {print $NF}')" \
  --title "chore: add sonar-fix automated SonarQube issue fixing" \
  --body "$(cat <<EOF
## sonar-fix Onboarding

This PR was automatically generated by [sonar-fix-onboarding](https://github.com/${ONBOARDING_REPO}) in response to issue #${ISSUE_NUMBER}.

${SONAR_NOTE}

### What's included

- \`.github/workflows/sonar-fix.yml\` — the sonar-fix caller workflow (${TRIGGER})
$([ -n "$CONFIG_OVERRIDES" ] && echo "- \`.github/sonar-fix-config.yml\` — your config overrides" || echo "- No config overrides — central defaults will apply")

### What was set up for you

- \`SONAR_TOKEN\` secret — scoped project analysis token for \`${PROJECT_KEY}\`
- \`SONAR_PROJECT_KEY\` variable — \`${PROJECT_KEY}\`
- \`SONAR_HOST_URL\` variable

### Next steps

1. Review the workflow file and adjust if needed
2. Merge this PR
3. Open a PR that introduces code with SonarQube issues to see sonar-fix in action

### AI agent

Fixes will be applied by **${AGENT}**.
To change the agent for your org, update the \`SONAR_FIX_AGENT\` variable in the sonar-fix-onboarding repo.

---
*Requested via [sonar-fix-onboarding#${ISSUE_NUMBER}](https://github.com/${ONBOARDING_REPO}/issues/${ISSUE_NUMBER})*
EOF
)"
