#!/usr/bin/env bash
# Opens an offboarding PR in the target repo to remove sonar-fix files.
# All inputs come from environment variables set by the calling workflow.
set -euo pipefail

BRANCH="sonar-fix/offboarding"

# ── Clone target repo ────────────────────────────────────────────────────────
git clone "https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git" /tmp/target-repo
cd /tmp/target-repo

git config user.email "github-actions[bot]@users.noreply.github.com"
git config user.name  "github-actions[bot]"

git config --unset-all http.https://github.com/.extraheader || true

# ── Create branch ─────────────────────────────────────────────────────────────
git checkout -B "$BRANCH"

# ── Remove sonar-fix files ────────────────────────────────────────────────────
REMOVED=()

for f in \
  ".github/workflows/sonar-fix.yml" \
  ".github/sonar-fix-config.yml"; do
  if [ -f "$f" ]; then
    git rm "$f"
    REMOVED+=("$f")
  fi
done

if [ ${#REMOVED[@]} -eq 0 ]; then
  echo "No sonar-fix files found to remove in ${TARGET_REPO}."
  exit 0
fi

# ── Commit and push ───────────────────────────────────────────────────────────
git commit -m "chore: remove sonar-fix automated issue fixing

Removed by sonar-fix-onboarding (issue ${ONBOARDING_REPO}#${ISSUE_NUMBER})."

git push --force-with-lease origin "$BRANCH"

# ── Open PR ───────────────────────────────────────────────────────────────────
gh pr create \
  --repo "$TARGET_REPO" \
  --head "$BRANCH" \
  --base "$(git remote show origin | awk '/HEAD branch/ {print $NF}')" \
  --title "chore: remove sonar-fix automated SonarQube issue fixing" \
  --body "$(cat <<EOF
## sonar-fix Offboarding

This PR was automatically generated by [sonar-fix-onboarding](https://github.com/${ONBOARDING_REPO}) in response to issue #${ISSUE_NUMBER}.

### What's removed

$(for f in "${REMOVED[@]}"; do echo "- \`$f\`"; done)

### What was already cleaned up

- \`SONAR_TOKEN\` secret — revoked and deleted
- \`SONAR_PROJECT_KEY\` variable — deleted
- \`SONAR_HOST_URL\` variable — deleted

Merge this PR to fully deactivate sonar-fix in this repository.

---
*Requested via [sonar-fix-onboarding#${ISSUE_NUMBER}](https://github.com/${ONBOARDING_REPO}/issues/${ISSUE_NUMBER})*
EOF
)"
